version: '3.6' 
  
volumes: 
  books_msql_data: 
  
services: 
  database: 
    env_file: .env 
    hostname: ${DB_HOST}
    image: mysql:8.2.0
    volumes: 
     - books_msql_data:/var/lib/${MYSQL_DATABASE}
  
  django_api: 
    env_file: .env 
    build: ./backend/ 
    depends_on: 
     - database 
    ports: 
     - 8000:8000
    volumes:
     - ./backend/:/app
    environment:
      DATABASE_URL: ${MYSQL_DATABASE}://${MYSQL_USER}:${MYSQL_PASSWORD}@mysql:${DB_PORT}/${MYSQL_DATABASE}
    command: >
      bash -c "
        until nc -z -v -w30 database ${DB_PORT} 2>/dev/null; do
          echo 'Ожидание MySQL...'
          sleep 2
        done && python manage.py makemigrations && python manage.py migrate && gunicorn --bind 0.0.0.0 backend.wsgi
      "

  redis:
    image: redis:7.2.3-alpine3.18
    hostname: redis

  worker:
    env_file: .env 
    build: ./backend/
    hostname: worker
    volumes:
      - ./backend/:/app
    links:
      - redis
    depends_on:
      - django_api
      - redis
    command: celery -A backend worker -l info
