version: '3.6' 
  
volumes: 
  pg: 
  
services: 
  database: 
    env_file: .env 
    image: postgres:16.1-alpine.18
    volumes: 
     - pg:/var/lib/postgresql/data/
  
  django_api: 
    env_file: .env 
    build: ./backend/ 
    depends_on: 
     - database 
    ports: 
     - 8000:8000
    volumes:
     - ./backend/:/backend

  redis:
    image: redis:7.2.3-alpine3.18
    hostname: redis

  worker:
    build:
      context: .
    hostname: worker
    entrypoint: celery
    command: -A celerr.app worker --loglevel=info
    volumes:
      - ./backend/:/backend
    links:
      - redis
    depends_on:
      - redis